Improve error message when a non-primitive is used
When a bad primitive was used, the error was not explicit at all:
```
File "e3/anod/context.py", line 509, in add_spec
    assert_never()
NameError: name 'assert_never' is not defined
```

IT-2217