Revert "Avoid using Optional for Env.main_options and Main.args."
This reverts commit 63aa8a78b3699c01071c3a2fe49afff55c029c2a.
The commit breaks many tools that dump the content of Env is a JSON
and we get errors such as:

TypeError: Object of type Namespace is not JSON serializable
TN: V930-018