Force setting of E3_ENABLE_FEATURE to have stable tests
Setting E3_ENABLE_FEATURE=smtp_ssl outside should not modify test
results. Force the export in conftest.py and mock SMTP_SSL.

Not doing that generates a failure when smtp_ssl is set:

  AttributeError: SMTP_SSL instance has no attribute 'local_hostname'